# Generated by Django 4.1 on 2022-08-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("age", models.IntegerField()),
                ("weight", models.FloatField()),
                (
                    "sex",
                    models.CharField(
                        choices=[
                            ("Macho", "Macho"),
                            ("Femea", "Femea"),
                            ("Não informado", "Other"),
                        ],
                        default="Não informado",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
